language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/scalingo.git"
  - secure: TT+PGPfKgVlXb/wKFEsk1d0rE94gAPPzy3VSX+n57Ws3serLZaG9CzZz5DJCBuaJAQv5R3bCDX2Kn3sv2RRlIUcDReH2ajmvkcueSrLUPK51iIAk/1YfboMHJ75JfoklmdXkcoUZisTasoJuMVU9qO1Hl6Q48NxFI4jnAZr+Kn3CBttYtW23xsSojyfOL3/jLB6LPlCe9WvtDhGw6ZXoD4NGs8859LPVn9EePe1T01kd6KF4sHx9Cfbql7EqXxIuj+PaRNSIpa0+rUeWOgj8Qe6brb7uU46lfQrW7q3R3KVotx+LnzpcgR9AqkHH7pqITEpZWKCrhg38BUedDS5jTDa5YxSK6cAMg/d0pz1fNRhkskBZbAtETFi1o+OPY/DtJqeG+4EoaofZmwDtdGOA9jHgGdIYF59FAYLqbN51Y0WX0p2VEnLjVSF2HtDUhXYpRA+lgzXdbbq95BgGLW1c22XEXky6jcaThtZJSKfcxIoEGZ4UV+/4RiH0W8jNefbkHPUygXvqb+7gwhmebFw25eIbwFqKVOZ14AJwbhlV1/43x3jbazqbX68dPP8WsnHf18CZi6jc+7c694mh1AFeawdq+AnJhg8X8JFt1ElT+mOfhsTMe8ecN5wg9ZQyY/Bruq/3O3Ei68QpANz+nOgQ8YMcYMBZ8PumEF5bNTnbUlQ=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
- yarn run check
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_b4e5492af9dc_key -iv $encrypted_b4e5492af9dc_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
