language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/scalingo.git"
  - secure: hc6wFAyKK/ykfl7APTM7DBmW8na2SvqqWljwlIJR6QlYAZJKjn+vQQAfzyYwLL0GMs0uoV5pRyRdS2gCP6D9MOrXDxeMRO1pd/OT2LyIQ2PY0xQyBTcdwvYycBA4DQlxfsGyFx2VkeWKq086/JfyiMAkgWgjMtKha6l++OOrV55FEunVWEZx65TxN0I91gFVS1aDeSM0OVoTccF3Ue2xp+DVNOsX8WwRUL2XqM1+c3ki1VPJDWJoCEPY2MzcTBx/8D0/F0ejT7I7tUz/a8HVnkNXm55pFOBzgBe8vUfViNOCqWYvKoCdLar3XjSK4VT7wD0xC297zfhQwS6NI+evIZtOohf420wVHv/AZ8Xi1Xnl8zgByibFH4P76p76iUYCpsPkQZwjPm674GdQ9A1jb5asYtqRMnrt4ylZiPJbgkWsalE19kQ1vHdD9AZdgGMVUY19iUR6shZ+lCTnTqHWeINIngPvXbA2rev0uhm+9VZ8urFEV6tblnzCMwR2P/sDvDQHgBOBhHQ9/UKyablLlI/wqmLj+k6pgG05WXD2c3jA75eDJui7ZdXqR/0saf0wMT6q9iGCqAAx+SPds6lherFFLt41q1MWAHwDZEQeHstx1KfyYJYVZtO/0rFVRc2Fxd7hSQV2mFyIxdGfqXf5ZLyvQNpSGJEwfKAf4Fl1ALo=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8fa1155864b8_key -iv $encrypted_8fa1155864b8_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
