language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/scalingo.git"
  - secure: EGYAdD6aeKcsO6ZTSzFRLGg2MiSLGX2AMpjogz8Mf6TLkVxW6cfeQBs3J2/XWZkUh5vwOT+Uq0uJdnzDFibbEbMDDbccuKF/1kWB9eZrvBpV6y/8jDQolmd2tYV4V6dXnBRS0wPey1v1AjLMFRrCH0P7mfrcX3Kh2rtYat8J/aQoIQ+/Da5wxGRp9Uk6RKFbqDYwY4Jr/tiejXWV8LHY4pV/poSvKJyasXCiabFm38yT/xFjM0Qm1r2LopRSNVhIrJY04GopyrN0ax+EFOSeReOEGGh/Gq0bvNdPoz/qJECc01Fty4adeGH4nAFT7bgnF2h/dU+40lYtCQIPvbmTB2irtFzE73Ui0SpN8NFJXMbpFHi3+nSt4PuYpNSqU/7ONZlnPtNVTuEfWTxKWo1FQ+8w4V1+5FxyAixu/GbyQurcD32AgBnMA2T37jzK//QFblaWVNMU0N/taRgn7cmCTbjfeTgri0nOs2sDsPlCGJdnSF4r5mzTg8kvyL5w6asbVDPcLI7kfJFJdplB6gPEP6Q4LgLdGu7/MxhC3pCCEYTvI+j3p8FaLTpcmuPVBoBESjCtcvoKM7nrp0CQx1H+2WTPfDt4LRugeIRoHlbO3lJUcRVtnwKcS5GA2oklWQjBjq646FLhSZ5DEX4Sq1p3tP8UEzoHmoyZkqPcArOFFcc=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8fa1155864b8_key -iv $encrypted_8fa1155864b8_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
