language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/scalingo.git"
  - secure: YHo/iOYSSKRk0qFi89rIkMgvgCaTj13zXGaz8a47pRKeOABJ+p9t6pDDdUvaFd9RqSn+1pN7qV9ctp3P8iZ+EXsV0mz9Ul1VfeBJaq0yqYPaY41+D7+OVAoyczJDytY1K+NQQv5p4Diki5nbFTq/ImPsQq6CJ0cxrZrTxaz33x3Oa7SxedpMH3a6SwNsPCOhXUtT/9VXuIdEyg+hTRULC6H6nwUvu24SiptzzeDTd00ePvnEmaPz1FQvZvQQHfTsvCquW7TXLbEifZ+nLNbFVRBECpdbTnLjUmuRVqKXCb9fBu1VMCEmwem5yNYgS3FkBjUlCB6B4HSvTnVw+agptnIkEj8pbiENRi90rzhOVHXJSIlqLOdn9dXnrwrLFFlkRLR9+3qi1IQBBPgdw28zFn+mN5mFBEy7K8YiwtZAyDLslM1l6GQYPTNbc7TDsNZH31pv2E3oB+lU/QgY7DVqCE1XdEuNlCVZ12o2H7dhDHt0H7aVMmy7GJ7V70q2y8MlY+6BRXkQ63jaQTrMUqK+V36XpPvBP8ov1v+Skv+Yh0xcjKZjw3Op35q9WpcGrn9/npkCv8BlfJ+fkxWePGxln/MuEFId/7rT7xmXsyVgLfjJMSD1y25Ck/UyLoW8sWNx8ZW3WIEKGySkyc43Ox8md4SWH/x1eTkOS51Rryxnt0g=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
- yarn run check
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_ef8b9ba382e8_key -iv $encrypted_ef8b9ba382e8_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
